<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\StockMovement;
use Illuminate\Database\Seeder;

class InventoryDemoSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect([
            [
                'name' => 'Electronics',
                'slug' => 'electronics',
                'description' => 'Electronic devices and accessories.',
            ],
            [
                'name' => 'Office',
                'slug' => 'office',
                'description' => 'Office supplies and workspace essentials.',
            ],
            [
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Add-ons and small everyday accessories.',
            ],
            [
                'name' => 'Clothes',
                'slug' => 'clothes',
                'description' => 'Apparel and clothing items.',
            ],
            [
                'name' => 'Hygiene',
                'slug' => 'hygiene',
                'description' => 'Personal care and hygiene products.',
            ],
            [
                'name' => 'Food',
                'slug' => 'food',
                'description' => 'Groceries and food items.',
            ],
        ])->mapWithKeys(function (array $category) {
            $model = Category::query()->create($category);

            return [$model->slug => $model];
        });

        $productsByCategory = [
            'electronics' => [
                [
                    'name' => 'Wireless Keyboard',
                    'sku' => 'ELC-001',
                    'description' => '2.4G wireless keyboard.',
                    'price' => 299.99,
                    'quantity' => 100,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Wireless Mouse',
                    'sku' => 'ELC-002',
                    'description' => 'Ergonomic wireless mouse.',
                    'price' => 149.99,
                    'quantity' => 80,
                    'min_quantity' => 8,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Bluetooth Headset',
                    'sku' => 'ELC-003',
                    'description' => 'Noise-isolating wireless headset.',
                    'price' => 499.00,
                    'quantity' => 45,
                    'min_quantity' => 6,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => '27-inch Monitor',
                    'sku' => 'ELC-004',
                    'description' => 'Full HD IPS desktop monitor.',
                    'price' => 1899.00,
                    'quantity' => 18,
                    'min_quantity' => 4,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Portable SSD 1TB',
                    'sku' => 'ELC-005',
                    'description' => 'High-speed portable SSD storage.',
                    'price' => 999.00,
                    'quantity' => 30,
                    'min_quantity' => 5,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Wi-Fi Router',
                    'sku' => 'ELC-006',
                    'description' => 'Dual-band wireless router.',
                    'price' => 649.50,
                    'quantity' => 25,
                    'min_quantity' => 5,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Smartphone Charger',
                    'sku' => 'ELC-007',
                    'description' => '20W fast wall charger.',
                    'price' => 119.00,
                    'quantity' => 120,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Webcam HD',
                    'sku' => 'ELC-008',
                    'description' => '1080p USB webcam for meetings.',
                    'price' => 259.00,
                    'quantity' => 40,
                    'min_quantity' => 6,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Power Bank 20000mAh',
                    'sku' => 'ELC-009',
                    'description' => 'High-capacity portable power bank.',
                    'price' => 329.00,
                    'quantity' => 60,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Laptop Cooling Pad',
                    'sku' => 'ELC-010',
                    'description' => 'Cooling pad with dual silent fans.',
                    'price' => 219.00,
                    'quantity' => 28,
                    'min_quantity' => 5,
                    'note' => 'Initial warehouse stock',
                ],
            ],
            'office' => [
                [
                    'name' => 'Office Chair',
                    'sku' => 'OFF-001',
                    'description' => 'Adjustable office chair.',
                    'price' => 1299.00,
                    'quantity' => 20,
                    'min_quantity' => 5,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Standing Desk',
                    'sku' => 'OFF-002',
                    'description' => 'Height-adjustable workstation desk.',
                    'price' => 2899.00,
                    'quantity' => 12,
                    'min_quantity' => 3,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Desk Lamp',
                    'sku' => 'OFF-003',
                    'description' => 'LED desk lamp with adjustable arm.',
                    'price' => 199.00,
                    'quantity' => 55,
                    'min_quantity' => 8,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'A4 Paper Ream',
                    'sku' => 'OFF-004',
                    'description' => '500-sheet white printer paper.',
                    'price' => 69.00,
                    'quantity' => 200,
                    'min_quantity' => 25,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Stapler',
                    'sku' => 'OFF-005',
                    'description' => 'Heavy-duty office stapler.',
                    'price' => 59.50,
                    'quantity' => 75,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Whiteboard Markers',
                    'sku' => 'OFF-006',
                    'description' => 'Pack of 4 assorted markers.',
                    'price' => 45.00,
                    'quantity' => 90,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Filing Cabinet',
                    'sku' => 'OFF-007',
                    'description' => 'Metal cabinet with 3 drawers.',
                    'price' => 1599.00,
                    'quantity' => 10,
                    'min_quantity' => 2,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Notebook Set',
                    'sku' => 'OFF-008',
                    'description' => 'Pack of 5 ruled notebooks.',
                    'price' => 85.00,
                    'quantity' => 110,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Paper Shredder',
                    'sku' => 'OFF-009',
                    'description' => 'Cross-cut shredder for office documents.',
                    'price' => 899.00,
                    'quantity' => 8,
                    'min_quantity' => 2,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Desk Organizer',
                    'sku' => 'OFF-010',
                    'description' => 'Mesh organizer for pens and documents.',
                    'price' => 79.00,
                    'quantity' => 65,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
            ],
            'accessories' => [
                [
                    'name' => 'USB-C Cable',
                    'sku' => 'ACC-001',
                    'description' => '1 meter USB-C fast charging cable.',
                    'price' => 89.50,
                    'quantity' => 150,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Laptop Stand',
                    'sku' => 'ACC-002',
                    'description' => 'Aluminum adjustable laptop stand.',
                    'price' => 349.00,
                    'quantity' => 35,
                    'min_quantity' => 6,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Phone Case',
                    'sku' => 'ACC-003',
                    'description' => 'Shock-absorbent protective phone case.',
                    'price' => 99.00,
                    'quantity' => 140,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Backpack',
                    'sku' => 'ACC-004',
                    'description' => 'Water-resistant laptop backpack.',
                    'price' => 429.00,
                    'quantity' => 42,
                    'min_quantity' => 7,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Screen Protector',
                    'sku' => 'ACC-005',
                    'description' => 'Tempered glass screen protection.',
                    'price' => 49.00,
                    'quantity' => 180,
                    'min_quantity' => 25,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Wireless Earbuds Case',
                    'sku' => 'ACC-006',
                    'description' => 'Protective silicone earbuds case.',
                    'price' => 69.00,
                    'quantity' => 85,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Keychain Flashlight',
                    'sku' => 'ACC-007',
                    'description' => 'Compact rechargeable keychain light.',
                    'price' => 39.00,
                    'quantity' => 95,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Travel Adapter',
                    'sku' => 'ACC-008',
                    'description' => 'Universal plug adapter for travel.',
                    'price' => 159.00,
                    'quantity' => 50,
                    'min_quantity' => 8,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Watch Strap',
                    'sku' => 'ACC-009',
                    'description' => 'Replacement silicone watch strap.',
                    'price' => 79.00,
                    'quantity' => 70,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Cable Organizer',
                    'sku' => 'ACC-010',
                    'description' => 'Reusable clips for cable management.',
                    'price' => 35.00,
                    'quantity' => 130,
                    'min_quantity' => 18,
                    'note' => 'Initial warehouse stock',
                ],
            ],
            'clothes' => [
                [
                    'name' => 'Basic T-Shirt',
                    'sku' => 'CLT-001',
                    'description' => 'Cotton crew-neck t-shirt.',
                    'price' => 89.00,
                    'quantity' => 120,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Denim Jeans',
                    'sku' => 'CLT-002',
                    'description' => 'Classic straight-fit denim jeans.',
                    'price' => 249.00,
                    'quantity' => 60,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Hoodie',
                    'sku' => 'CLT-003',
                    'description' => 'Fleece-lined pullover hoodie.',
                    'price' => 199.00,
                    'quantity' => 50,
                    'min_quantity' => 8,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Sports Jacket',
                    'sku' => 'CLT-004',
                    'description' => 'Lightweight zip-up sports jacket.',
                    'price' => 329.00,
                    'quantity' => 28,
                    'min_quantity' => 5,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Sneakers',
                    'sku' => 'CLT-005',
                    'description' => 'Casual everyday sneakers.',
                    'price' => 399.00,
                    'quantity' => 40,
                    'min_quantity' => 6,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Socks Pack',
                    'sku' => 'CLT-006',
                    'description' => 'Pack of 5 cotton socks.',
                    'price' => 59.00,
                    'quantity' => 140,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Baseball Cap',
                    'sku' => 'CLT-007',
                    'description' => 'Adjustable cotton baseball cap.',
                    'price' => 75.00,
                    'quantity' => 75,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Formal Shirt',
                    'sku' => 'CLT-008',
                    'description' => 'Long-sleeve button-up shirt.',
                    'price' => 179.00,
                    'quantity' => 48,
                    'min_quantity' => 8,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Winter Scarf',
                    'sku' => 'CLT-009',
                    'description' => 'Soft knit winter scarf.',
                    'price' => 69.00,
                    'quantity' => 52,
                    'min_quantity' => 9,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Training Shorts',
                    'sku' => 'CLT-010',
                    'description' => 'Breathable athletic training shorts.',
                    'price' => 119.00,
                    'quantity' => 68,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
            ],
            'hygiene' => [
                [
                    'name' => 'Hand Soap',
                    'sku' => 'HYG-001',
                    'description' => 'Liquid hand soap dispenser refill.',
                    'price' => 35.00,
                    'quantity' => 160,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Toothpaste',
                    'sku' => 'HYG-002',
                    'description' => 'Fluoride toothpaste for daily use.',
                    'price' => 28.00,
                    'quantity' => 180,
                    'min_quantity' => 25,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Shampoo',
                    'sku' => 'HYG-003',
                    'description' => 'Moisturizing shampoo bottle.',
                    'price' => 54.00,
                    'quantity' => 95,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Body Wash',
                    'sku' => 'HYG-004',
                    'description' => 'Refreshing body wash gel.',
                    'price' => 59.00,
                    'quantity' => 90,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Toilet Paper Pack',
                    'sku' => 'HYG-005',
                    'description' => '12-roll toilet paper pack.',
                    'price' => 89.00,
                    'quantity' => 130,
                    'min_quantity' => 18,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Paper Towels',
                    'sku' => 'HYG-006',
                    'description' => 'Absorbent kitchen paper towels.',
                    'price' => 74.00,
                    'quantity' => 100,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Sanitizer Gel',
                    'sku' => 'HYG-007',
                    'description' => 'Alcohol-based hand sanitizer gel.',
                    'price' => 32.00,
                    'quantity' => 150,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Disposable Razors',
                    'sku' => 'HYG-008',
                    'description' => 'Pack of disposable razors.',
                    'price' => 49.00,
                    'quantity' => 88,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Cotton Swabs',
                    'sku' => 'HYG-009',
                    'description' => 'Box of 200 cotton swabs.',
                    'price' => 19.00,
                    'quantity' => 140,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Facial Tissues',
                    'sku' => 'HYG-010',
                    'description' => 'Soft 2-ply facial tissues.',
                    'price' => 24.00,
                    'quantity' => 120,
                    'min_quantity' => 18,
                    'note' => 'Initial warehouse stock',
                ],
            ],
            'food' => [
                [
                    'name' => 'Rice 5kg',
                    'sku' => 'FOD-001',
                    'description' => 'Premium long-grain rice bag.',
                    'price' => 149.00,
                    'quantity' => 90,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Pasta Pack',
                    'sku' => 'FOD-002',
                    'description' => 'Durum wheat pasta pack.',
                    'price' => 22.00,
                    'quantity' => 170,
                    'min_quantity' => 25,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Olive Oil 1L',
                    'sku' => 'FOD-003',
                    'description' => 'Extra virgin olive oil bottle.',
                    'price' => 119.00,
                    'quantity' => 75,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Tomato Sauce',
                    'sku' => 'FOD-004',
                    'description' => 'Ready-to-cook tomato sauce jar.',
                    'price' => 18.50,
                    'quantity' => 140,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Tuna Cans',
                    'sku' => 'FOD-005',
                    'description' => 'Pack of canned tuna.',
                    'price' => 56.00,
                    'quantity' => 110,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Breakfast Cereal',
                    'sku' => 'FOD-006',
                    'description' => 'Whole grain cereal box.',
                    'price' => 44.00,
                    'quantity' => 85,
                    'min_quantity' => 12,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Coffee Beans',
                    'sku' => 'FOD-007',
                    'description' => 'Medium roast whole coffee beans.',
                    'price' => 95.00,
                    'quantity' => 65,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Green Tea Box',
                    'sku' => 'FOD-008',
                    'description' => 'Box of green tea bags.',
                    'price' => 31.00,
                    'quantity' => 100,
                    'min_quantity' => 15,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Sugar 1kg',
                    'sku' => 'FOD-009',
                    'description' => 'Refined white sugar pack.',
                    'price' => 16.00,
                    'quantity' => 150,
                    'min_quantity' => 20,
                    'note' => 'Initial warehouse stock',
                ],
                [
                    'name' => 'Milk Powder',
                    'sku' => 'FOD-010',
                    'description' => 'Instant full cream milk powder.',
                    'price' => 72.00,
                    'quantity' => 70,
                    'min_quantity' => 10,
                    'note' => 'Initial warehouse stock',
                ],
            ],
        ];

        foreach ($productsByCategory as $categorySlug => $products) {
            $category = $categories->get($categorySlug);

            foreach ($products as $productData) {
                $product = Product::query()->create([
                    'name' => $productData['name'],
                    'sku' => $productData['sku'],
                    'description' => $productData['description'],
                    'price' => $productData['price'],
                    'quantity' => $productData['quantity'],
                    'min_quantity' => $productData['min_quantity'],
                    'category_id' => $category->id,
                ]);

                StockMovement::query()->create([
                    'product_id' => $product->id,
                    'order_id' => null,
                    'type' => 'stock_in',
                    'quantity' => $productData['quantity'],
                    'note' => $productData['note'],
                ]);
            }
        }
    }
}
